# Site Settings
title: Fabio Rangel
url: 'fabiorangel.github.io'
baseurl: 'fabiorangel.github.io' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Fabio Rangel
tagline: Researcher and Data Scientist
pic: foto.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Fabio Rangel holds B.S. in Computer Science from the Federal University of Rio de Janeiro (2015). Currently a graduate (master) student at the Graduate Program in Informatics at UFRJ (PPGI - UFRJ). His research is associated with Machine Learning in Nonstationary Environments, focusing in Semi-Supervised and Online Learning. Fabio is also a part-time lecturer at the same university, teaching Programming, Linear Algebra, and Computational Intelligence. Fabio also supervised the scientific initiation work entitled Predicting Performance of ENEM Candidates Through Socioeconomic Data, selected as one of the nine best works of IC in Brazil by the 36th Scientific Initiation Work Contest (2017).'

#sidebar links
email: fabiorangel at dcc ufrj br
#phone: 012 345 6789
#website: blog.webjeda.com #do not add http://
#linkedin: alandoe
github: fabiorangel
twitter: '@fabiomrangel'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
